// <auto-generated />
using System;
using Accountant.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accountant.MySql.Migrations
{
    [DbContext(typeof(AccountantDbContext))]
    [Migration("20260510144232_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Accountant.DataAccess.Entities.EvaluationDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CriticalMatchCount")
                        .HasColumnType("int");

                    b.Property<int>("CriticalMismatchCount")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationRunId")
                        .HasColumnType("int");

                    b.Property<long?>("ExtractionId")
                        .HasColumnType("bigint");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<int>("MismatchCount")
                        .HasColumnType("int");

                    b.Property<string>("MismatchesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("MoneyMatchCount")
                        .HasColumnType("int");

                    b.Property<int>("MoneyMismatchCount")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionId");

                    b.HasIndex("PromptVersion");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("EvaluationRunId", "Vendor");

                    b.ToTable("evaluation_documents", (string)null);
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.EvaluationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("RunAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RunAtUtc");

                    b.ToTable("evaluation_runs", (string)null);
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.Extraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CostEstimateUsd")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("OcrUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Pipeline")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StopReason")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("ValidationFailCount")
                        .HasColumnType("int");

                    b.Property<bool>("ValidationNeedsReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ValidationWarnCount")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("PromptVersion");

                    b.HasIndex("SourceDocumentId", "Vendor", "StartedAtUtc");

                    b.ToTable("extractions", (string)null);
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.GroundTruth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtractionJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastEditedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastEditedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceDocumentId")
                        .IsUnique();

                    b.ToTable("ground_truths", (string)null);
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.SourceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("FileName");

                    b.ToTable("source_documents", (string)null);
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.EvaluationDocument", b =>
                {
                    b.HasOne("Accountant.DataAccess.Entities.EvaluationRun", "EvaluationRun")
                        .WithMany("Documents")
                        .HasForeignKey("EvaluationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accountant.DataAccess.Entities.Extraction", "Extraction")
                        .WithMany()
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accountant.DataAccess.Entities.SourceDocument", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvaluationRun");

                    b.Navigation("Extraction");

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.Extraction", b =>
                {
                    b.HasOne("Accountant.DataAccess.Entities.SourceDocument", "SourceDocument")
                        .WithMany("Extractions")
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.GroundTruth", b =>
                {
                    b.HasOne("Accountant.DataAccess.Entities.SourceDocument", "SourceDocument")
                        .WithOne("GroundTruth")
                        .HasForeignKey("Accountant.DataAccess.Entities.GroundTruth", "SourceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.EvaluationRun", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Accountant.DataAccess.Entities.SourceDocument", b =>
                {
                    b.Navigation("Extractions");

                    b.Navigation("GroundTruth");
                });
#pragma warning restore 612, 618
        }
    }
}
